language: go

go:
  - "1.12"
  - tip

notifications:
  email: false

env:
  global:
    # Coveralls.io token.
    - secure: "YZKB1SLTzPJMOdXp5U3xwEsh4++Xe8EeVK8SZVEQkn/y4xCbzmbdo6BJ4B/eGBG6bK4DLzFD3sb6uaUB2bHlVUXnR8YHbetjps6PUwLYtX9UdcBjB7UN5tdQs1d8k2qg7vPNtKVEY4kJHFURijc4Kk+zlNbq1oGJcEfm6gz+zGg="

install:
  - go get -t ./...

before_script:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  # TODO: re-enable when https://github.com/golangci/golangci-lint/issues/595 is resolved.
  #- go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - wget https://raw.githubusercontent.com/mewmew/ci/master/ci_checks.sh
  - chmod +x ci_checks.sh

script:
  - ./ci_checks.sh
